In [ ]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')
file_path = "/content/drive/MyDrive/AI03 GP/Autoimmune_Disorder_10k_with_All_Disorders.csv"
df = pd.read_csv(file_path)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Patient_ID  Age  Gender                                        Diagnosis  \
0           1   65  Female                               Linear IgA disease   
1           2   61    Male                                  Dermatomyositis   
2           3   42    Male                                Ord's thyroiditis   
3           4   45  Female                           Restless legs syndrome   
4           5   78  Female  Autoimmune polyendocrine syndrome type 2 (APS2)   

   Sickness_Duration_Months  RBC_Count  Hemoglobin  Hematocrit    MCV    MCH  \
0                        26       3.54       13.18       44.35  99.85  31.80   
1                       106       4.97       14.73       42.39  94.86  29.94   
2                         6       3.91       13.66       42.41  88.26  29.43   
3                        11       4.57       14.96       40.10  85.95  27.42   
4                        30       4.88       11.21       37.58  93.16  29.87   

   ...  Anti_TIF1  Anti_epidermal_basement_membrane_IgA  Anti_OmpC  pANCA  \
0  ...          0                                     1          0      0   
1  ...          1                                     0          0      0   
2  ...          0                                     0          0      0   
3  ...          0                                     0          0      0   
4  ...          0                                     0          0      0   

   Anti_tissue_transglutaminase  anti_Scl_70  Anti_Mi2  Anti_parietal_cell  \
0                             0            0         0                   0   
1                             0            0         1                   0   
2                             0            0         0                   0   
3                             0            0         0                   0   
4                             0            0         0                   0   

   Progesterone_antibodies  Anti_Sm  
0                        0        0  
1                        0        0  
2                        0        0  
3                        0        0  
4                        0        0  

[5 rows x 79 columns]

In [ ]:
cols_to_keep = [
    "Patient_ID",
    "Age",
    "Gender",
    "Diagnosis",
    "Sickness_Duration_Months",
    "Low-grade fever",
    "Fatigue or chronic tiredness",
    "Dizziness",
    "Weight loss",
    "Rashes and skin lesions",
    "Stiffness in the joints",
    "Brittle hair or hair loss",
    "Dry eyes and/or mouth",
    "General 'unwell' feeling",
    "Joint pain"
]

df = df[cols_to_keep]


In [ ]:
df.columns


Index(['Patient_ID', 'Age', 'Gender', 'Diagnosis', 'Sickness_Duration_Months',
       'Low-grade fever', 'Fatigue or chronic tiredness', 'Dizziness',
       'Weight loss', 'Rashes and skin lesions', 'Stiffness in the joints',
       'Brittle hair or hair loss', 'Dry eyes and/or mouth',
       'General 'unwell' feeling', 'Joint pain'],
      dtype='object')

In [ ]:
df.isnull().sum()



Patient_ID                      0
Age                             0
Gender                          0
Diagnosis                       0
Sickness_Duration_Months        0
Low-grade fever                 0
Fatigue or chronic tiredness    0
Dizziness                       0
Weight loss                     0
Rashes and skin lesions         0
Stiffness in the joints         0
Brittle hair or hair loss       0
Dry eyes and/or mouth           0
General 'unwell' feeling        0
Joint pain                      0
dtype: int64

In [ ]:
df.head()

Patient_ID  Age  Gender                                        Diagnosis  \
0           1   65  Female                               Linear IgA disease   
1           2   61    Male                                  Dermatomyositis   
2           3   42    Male                                Ord's thyroiditis   
3           4   45  Female                           Restless legs syndrome   
4           5   78  Female  Autoimmune polyendocrine syndrome type 2 (APS2)   

   Sickness_Duration_Months  Low-grade fever  Fatigue or chronic tiredness  \
0                        26                0                             1   
1                       106                1                             0   
2                         6                0                             1   
3                        11                1                             0   
4                        30                0                             1   

   Dizziness  Weight loss  Rashes and skin lesions  Stiffness in the joints  \
0          1            0                        0                        0   
1          0            1                        1                        0   
2          1            0                        1                        0   
3          1            1                        1                        0   
4          1            1                        0                        1   

   Brittle hair or hair loss  Dry eyes and/or mouth  General 'unwell' feeling  \
0                          0                      0                         1   
1                          1                      0                         0   
2                          0                      0                         0   
3                          1                      1                         1   
4                          0                      0                         1   

   Joint pain  
0           1  
1           1  
2           0  
3           0  
4           0

In [ ]:
df["Diagnosis"] = df["Diagnosis"].apply(
    lambda x: 0 if str(x).strip().lower() == "normal" else 1
)


In [ ]:
df.head()

Patient_ID  Age  Gender  Diagnosis  Sickness_Duration_Months  \
0           1   65  Female          1                        26   
1           2   61    Male          1                       106   
2           3   42    Male          1                         6   
3           4   45  Female          1                        11   
4           5   78  Female          1                        30   

   Low-grade fever  Fatigue or chronic tiredness  Dizziness  Weight loss  \
0                0                             1          1            0   
1                1                             0          0            1   
2                0                             1          1            0   
3                1                             0          1            1   
4                0                             1          1            1   

   Rashes and skin lesions  Stiffness in the joints  \
0                        0                        0   
1                        1                        0   
2                        1                        0   
3                        1                        0   
4                        0                        1   

   Brittle hair or hair loss  Dry eyes and/or mouth  General 'unwell' feeling  \
0                          0                      0                         1   
1                          1                      0                         0   
2                          0                      0                         0   
3                          1                      1                         1   
4                          0                      0                         1   

   Joint pain  
0           1  
1           1  
2           0  
3           0  
4           0

In [ ]:
df.head()

Patient_ID  Age  Gender  Diagnosis  Sickness_Duration_Months  \
0           1   65  Female          1                        26   
1           2   61    Male          1                       106   
2           3   42    Male          1                         6   
3           4   45  Female          1                        11   
4           5   78  Female          1                        30   

   Low-grade fever  Fatigue or chronic tiredness  Dizziness  Weight loss  \
0                0                             1          1            0   
1                1                             0          0            1   
2                0                             1          1            0   
3                1                             0          1            1   
4                0                             1          1            1   

   Rashes and skin lesions  Stiffness in the joints  \
0                        0                        0   
1                        1                        0   
2                        1                        0   
3                        1                        0   
4                        0                        1   

   Brittle hair or hair loss  Dry eyes and/or mouth  General 'unwell' feeling  \
0                          0                      0                         1   
1                          1                      0                         0   
2                          0                      0                         0   
3                          1                      1                         1   
4                          0                      0                         1   

   Joint pain  
0           1  
1           1  
2           0  
3           0  
4           0

In [ ]:
df.drop_duplicates(inplace=True)


In [ ]:
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})


In [ ]:
from sklearn.preprocessing import StandardScaler

# Binary columns (never scale)
binary_cols = [
    "Diagnosis",
    "Gender",
    "Low-grade fever",
    "Fatigue or chronic tiredness",
    "Dizziness",
    "Weight loss",
    "Rashes and skin lesions",
    "Stiffness in the joints",
    "Brittle hair or hair loss",
    "Dry eyes and/or mouth",
    "General 'unwell' feeling",
    "Joint pain"
]

# Columns to scale (explicitly exclude Sickness_Duration_Months)
scale_cols = [
    col for col in df.select_dtypes(include=["int64", "float64"]).columns
    if col not in binary_cols and col != "Sickness_Duration_Months"
]

scaler = StandardScaler()
df[scale_cols] = scaler.fit_transform(df[scale_cols])


In [ ]:
df.drop(columns=["Patient_ID"], inplace=True)


In [ ]:
df.info()
df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Age                           12500 non-null  float64
 1   Gender                        12500 non-null  int64  
 2   Diagnosis                     12500 non-null  int64  
 3   Sickness_Duration_Months      12500 non-null  int64  
 4   Low-grade fever               12500 non-null  int64  
 5   Fatigue or chronic tiredness  12500 non-null  int64  
 6   Dizziness                     12500 non-null  int64  
 7   Weight loss                   12500 non-null  int64  
 8   Rashes and skin lesions       12500 non-null  int64  
 9   Stiffness in the joints       12500 non-null  int64  
 10  Brittle hair or hair loss     12500 non-null  int64  
 11  Dry eyes and/or mouth         12500 non-null  int64  
 12  General 'unwell' feeling      12500 non-null  int64  
 13  J

Age  Gender  Diagnosis  Sickness_Duration_Months  Low-grade fever  \
0  0.859243       1          1                        26                0   
1  0.633763       0          1                       106                1   
2 -0.437263       0          1                         6                0   
3 -0.268153       1          1                        11                1   
4  1.592050       1          1                        30                0   

   Fatigue or chronic tiredness  Dizziness  Weight loss  \
0                             1          1            0   
1                             0          0            1   
2                             1          1            0   
3                             0          1            1   
4                             1          1            1   

   Rashes and skin lesions  Stiffness in the joints  \
0                        0                        0   
1                        1                        0   
2                        1                        0   
3                        1                        0   
4                        0                        1   

   Brittle hair or hair loss  Dry eyes and/or mouth  General 'unwell' feeling  \
0                          0                      0                         1   
1                          1                      0                         0   
2                          0                      0                         0   
3                          1                      1                         1   
4                          0                      0                         1   

   Joint pain  
0           1  
1           1  
2           0  
3           0  
4           0

In [ ]:
df["Diagnosis"].value_counts(normalize=True)


Diagnosis
1    0.8
0    0.2
Name: proportion, dtype: float64

In [ ]:
df_before_outliers = df.copy()


In [ ]:
df_before_outliers["Diagnosis"].value_counts()


Diagnosis
1    10000
0     2500
Name: count, dtype: int64

In [ ]:
df.head()


Age  Gender  Diagnosis  Sickness_Duration_Months  Low-grade fever  \
0  0.859243       1          1                        26                0   
1  0.633763       0          1                       106                1   
2 -0.437263       0          1                         6                0   
3 -0.268153       1          1                        11                1   
4  1.592050       1          1                        30                0   

   Fatigue or chronic tiredness  Dizziness  Weight loss  \
0                             1          1            0   
1                             0          0            1   
2                             1          1            0   
3                             0          1            1   
4                             1          1            1   

   Rashes and skin lesions  Stiffness in the joints  \
0                        0                        0   
1                        1                        0   
2                        1                        0   
3                        1                        0   
4                        0                        1   

   Brittle hair or hair loss  Dry eyes and/or mouth  General 'unwell' feeling  \
0                          0                      0                         1   
1                          1                      0                         0   
2                          0                      0                         0   
3                          1                      1                         1   
4                          0                      0                         1   

   Joint pain  
0           1  
1           1  
2           0  
3           0  
4           0

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, average_precision_score
)

In [ ]:

# 1) Split features/target
target_col = "Diagnosis"   # change if yours is lowercase
X = df.drop(columns=[target_col])
y = df[target_col].astype(int)

# Stratified split (keeps the 80/20 ratio in train/test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
# 2) Train models (imbalance handled via class_weight)
log_reg = LogisticRegression(
    class_weight="balanced",
    max_iter=2000,
    solver="liblinear"
)

rf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    class_weight="balanced_subsample",
    n_jobs=-1
)

log_reg.fit(X_train, y_train)
rf.fit(X_train, y_train)


RandomForestClassifier(class_weight='balanced_subsample', n_estimators=500,
                       n_jobs=-1, random_state=42)

In [ ]:
# 3) Evaluation helper
def eval_model(name, model, X_test, y_test):
    y_pred = model.predict(X_test)

    # for AUCs we need probabilities (most sklearn classifiers support this)
    y_proba = model.predict_proba(X_test)[:, 1]

    print(f"\n==================== {name} ====================")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, digits=4))
    print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.4f}")
    print(f"PR-AUC : {average_precision_score(y_test, y_proba):.4f}")

eval_model("Logistic Regression", log_reg, X_test, y_test)
eval_model("Random Forest", rf, X_test, y_test)


==================== Logistic Regression ====================
Confusion Matrix:
[[ 500    0]
 [   1 1999]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9980    1.0000    0.9990       500
           1     1.0000    0.9995    0.9997      2000

    accuracy                         0.9996      2500
   macro avg     0.9990    0.9998    0.9994      2500
weighted avg     0.9996    0.9996    0.9996      2500

ROC-AUC: 1.0000
PR-AUC : 1.0000

==================== Random Forest ====================
Confusion Matrix:
[[ 500    0]
 [   0 2000]]

Classification Report:
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000       500
           1     1.0000    1.0000    1.0000      2000

    accuracy                         1.0000      2500
   macro avg     1.0000    1.0000    1.0000      2500
weighted avg     1.0000    1.0000    1.0000      2500

ROC-AUC: 1.0000
PR-AUC : 1.0000


In [ ]:
# choose a threshold (e.g., 0.35 instead of 0.5)
th = 0.35
proba = log_reg.predict_proba(X_test)[:, 1]
y_pred_th = (proba >= th).astype(int)

print(confusion_matrix(y_test, y_pred_th))
print(classification_report(y_test, y_pred_th, digits=4))


[[ 500    0]
 [   1 1999]]
              precision    recall  f1-score   support

           0     0.9980    1.0000    0.9990       500
           1     1.0000    0.9995    0.9997      2000

    accuracy                         0.9996      2500
   macro avg     0.9990    0.9998    0.9994      2500
weighted avg     0.9996    0.9996    0.9996      2500



In [ ]:
import pandas as pd

corr = df.corr()["Diagnosis"].sort_values(ascending=False)
print(corr)


Diagnosis                       1.000000
Sickness_Duration_Months        0.614419
Brittle hair or hair loss       0.411591
Low-grade fever                 0.409338
Dry eyes and/or mouth           0.406549
Weight loss                     0.404922
Joint pain                      0.404787
General 'unwell' feeling        0.403637
Dizziness                       0.402894
Rashes and skin lesions         0.400535
Stiffness in the joints         0.400131
Fatigue or chronic tiredness    0.399862
Gender                         -0.006080
Age                            -0.034368
Name: Diagnosis, dtype: float64


In [ ]:
df.groupby("Diagnosis").sum()


Age  Gender  Sickness_Duration_Months  Low-grade fever  \
Diagnosis                                                                  
0          171.837696    1252                         0                0   
1         -171.837696    4932                    599562             5016   

           Fatigue or chronic tiredness  Dizziness  Weight loss  \
Diagnosis                                                         
0                                     0          0            0   
1                                  4876       4921         4951   

           Rashes and skin lesions  Stiffness in the joints  \
Diagnosis                                                     
0                                0                        0   
1                             4886                     4880   

           Brittle hair or hair loss  Dry eyes and/or mouth  \
Diagnosis                                                     
0                                  0                      0   
1                               5049                   4975   

           General 'unwell' feeling  Joint pain  
Diagnosis                                        
0                                 0           0  
1                              4932        4949

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(log_reg, X, y, cv=cv, scoring="roc_auc")
print(scores, scores.mean())


[1. 1. 1. 1. 1.] 1.0


In [ ]:
from sklearn.utils import shuffle

y_perm = shuffle(y, random_state=42)

log_reg.fit(X_train, y_perm[:len(X_train)])
y_pred = log_reg.predict(X_test)

print(confusion_matrix(y_test, y_pred))


#[[TN  FP]
#[FN  TP]]

[[   0  500]
 [1142  858]]
